# Generated by Django 5.0.1 on 2024-01-31 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
